export const books = [
  { id: 1, title: "Harry Potter and the Philosopher's Stone" },
  { id: 2, title: "The Lord of the Rings" },
  { id: 3, title: "To Kill a Mockingbird" },
  { id: 4, title: "The Catcher in the Rye" },
  { id: 5, title: "1984" },
  { id: 6, title: "Pride and Prejudice" },
  { id: 7, title: "The Great Gatsby" },
  { id: 8, title: "One Hundred Years of Solitude" },
  { id: 9, title: "The Hobbit" },
  { id: 10, title: "The Chronicles of Narnia" },
  { id: 11, title: "The Hitchhiker's Guide to the Galaxy" },
  { id: 12, title: "Animal Farm" },
  { id: 13, title: "Brave New World" },
  { id: 14, title: "The Picture of Dorian Gray" },
  { id: 15, title: "Wuthering Heights" },
  { id: 16, title: "Dracula" },
  { id: 17, title: "Frankenstein" },
  { id: 18, title: "The Adventures of Sherlock Holmes" },
  { id: 19, title: "The War of the Worlds" },
  { id: 20, title: "Treasure Island" },
  { id: 21, title: "Alice's Adventures in Wonderland" },
  { id: 22, title: "Moby-Dick" },
  { id: 23, title: "Don Quixote" },
  { id: 24, title: "The Three Musketeers" },
  { id: 25, title: "Les Misérables" },
  // Adicione mais livros aqui se desejar...
];
